Namwoosung/algorithm_daejeon6_hard

.idea/algorithm_daejeon6_hard.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
jeonghun/week01/d_20250721/test.java
박정훈/1차시/10164.java
박정훈/2차시/BOJ_1325.java
박정훈/2차시/BOJ_3584.java

- 문제 링크 : [바로가기](https://www.acmicpc.net/problem/10164)
- O(N*M), 메모리 (11536KB), 시간 (72ms)
<br>
> 시작점부터 왼쪽과 위의 dp를 통해 현재 위치 dp 업데이트
> K의 인덱스 번호를 미리 구한 후 해당 인덱스를 기준으로 도착하지 않는 곳의 dp는 0으로 유지, 이후 왼, 위의 dp배열값을 더해 현재 dp 업데이트
> K의 인덱스를 깔끔하게 구하는 공식 -> K 인덱스 값을 여러 번 틀림
> K가 0일 때를 고려하지 못 하고 여러 번 시도함
<br>

[1차시] 박정훈 - 백준 10164

---

박정훈/2차시/BOJ_1325.java
박정훈/2차시/BOJ_3584.java
박정훈/3차시/BOJ_1138.java
박정훈/3차시/BOJ_21758.java

- 문제 링크 : [1325번 효율적인 해킹](https://www.acmicpc.net/problem/1325)
- 메모리: 141780KB
- 시간: 9612ms
- 시간 복잡도: O(N^2)
<br>
모든 컴퓨터를 시작점으로 해킹할 수 있는 컴퓨터 수를 카운트
- 모든 컴퓨터를 시작으로 그래프를 dfs 수행하며 방문하지 않은 컴퓨터가 있다면 count
- count가 N이 되면 탐색 중지
- 모든 컴퓨터를 시작점으로 탐색을 마쳤다면 가장 많이 해킹할 수 있는 컴퓨터 출력
시간 복잡도 계산이 맞는 지, 더 효율적인 풀이 방법이 있는 지
> X
<br>
- 문제 링크 : [3584번 가장 가까운 공통 조상](https://www.acmicpc.net/problem/3584)
- 메모리: 27320KB
- 시간: 184ms
- 시간 복잡도: O(N)
<br>
한 노드에서 먼저 dfs 수행하며 노드 방문 체크 -> 이후 다음 노드에서 dfs 하며 방문한 노드 발견 시 반환
- 두 개의 노드 중 한 개의 노드에서 먼저 dfs 수행하며 방문 체크 -> root 노드까지 방문
- 다른 노드에서 dfs 수행하며 방문한 노드가 있다면 해당 노드 반환
한 쪽을 먼저 루트까지 가지 않고 양쪽에서 동시에 하는 방법이 있을까요?
> X
<br>

[2차시] 박정훈 - 1325번 효율적인 해킹, 3584번 가장 가까운 공통 조상

---

남우성/3차시/1138.java
남우성/3차시/21758.java

- 문제 링크 : [1138 한 줄로 서기](https://www.acmicpc.net/problem/1138)
- 메모리: 14,148KB
- 시간: 104 ms
- 분석한 시간복잡도: O(N^2)
- 이유: 각 사람별로 탐색하며, 각 탐색마다 자신의 위치를 확정하기 위해 N 길이 배열 탐색 ⇒ O(N^2)
<br>
- 처음에 고민 좀 하긴 했는데, 그리디가 바로 떠올라서 그리디로 풀이
- 좀 더 적합한 방식이 있나 고민했는데, 사실 입력값 범위가 10이라 어떤 알고리즘으로 풀어도 풀리긴할거라 떠오른 그리디로 풀이 시작
- 문제 분석 및 나의 풀이
- 키가 작은 사람부터 탐색
- 각자 자신보다 키 큰 사람의 개수 만큼 앞의 자리를 확보하고 다음 자리로 들어감
(이미 사람이 있는 경우는 count X)
- 사용한 알고리즘 및 자료구조
- 그리디로 풀이
- 빈자리를 찾을 때, Segment Tree / Binary Indexed Tree 등을 사용하면 N이 아니라 logN 으로 가능할 것도 같긴 한데, 아직 위의 2개는 내공이 부족해서 확실히는 모르겠슴다… 
<br><br>
- 문제 링크 : [21758 꿀 따](https://www.acmicpc.net/problem/21758)
- 메모리: 24,808KB
- 시간: 256 ms
- 분석한 시간복잡도: O(N)
- 이유: case를 3번 나누고 돌려서 3N이라 O(N), 꿀을 더하는 과정은 연산 2번 정도만 들어가서 O(1)
<br>
- 처음에는 완전탐색인데(O(N^2))으로 생각, case를 3개로 나누는 건 똑같은데 꿀을 더하는 과정에서 N번 반복문을 …

3차시 namws code submit

---

천보성/4차시/BOJ_12919.java
천보성/4차시/BOJ_15954.java

- 문제 링크 : (https://www.acmicpc.net/problem/15954)
<br>
> 처음에는 단순하게 브루트포스로 접근해서 풀려고 했습니다.
그러나 최적화를 시키고 싶은 마음에 점점 수학적으로 접근을 했고
분산의 공식에 대해서 최적화 시키는 방법으로 갔습니다.  
> 
글로 풀기가 힘들어서 사진을 첨부하겠습니다..
수식을 정리해서 방식 1을 적용해본 결과 double 연산 과정에서 부동소수점으로 인한 오차에 많은 오류가 있었습니다.
다르게 생각해서 방식 2로 수식을 정리해서 적용을 한 결과 보다 정확한 계산을 할 수 있었습니다.
누적합 배열 1개, 제곱 누적합 배열 1개를 사용해서 풀이를 해보았습니다.
> 소수점에 따른 오차가 생각보다 크네요.. BigDecimal 쓰고 싶었지만 성능 때문에 참고 고쳤습니다..
<br>
- 문제 링크 : (https://www.acmicpc.net/problem/12919)
- 해시맵 적용 전
- 해시맵 적용 후
<br>
>  이러한 문제는 조건문으로 가지치기가 가장 중요하다고 생각을 했습니다.
문자열에 대해 역순으로 접근을 하면 순방향과 마찬가지로 최대 2가지인 것은 맞지만
조건문으로 가지 치기가 더 수월하다고 생각했습니다.
또 A와 B의 개수를 세서 그 부분 또한 가지치기를 진행했습니다.
HashSet 도 사용하여 이미 접근한 문자열에 대해서도 가지치기를 진행했습니다.
(이 부분은 우성님 PR을 보고 아이디어를 얻어 진행했습니다.)
> 문자열에 대해 역순으로 접근,
count 변수들을 통해 가지치기, HashSet을 사용해 이미 방문한 곳 가지치기 
> …

[4차시] 천보성 - BOJ_15954, BOJ_12919

---

안도형/2차시/BOJ_1325.java
안도형/2차시/BOJ_3584.java

> [!IMPORTANT]
> PR 제목 양식 :  [weekXX] 이름 - 문제 제목
> 작성 후 삭제해주세요
- 문제 링크 : [바로가기](이곳에 링크를 넣어 주세요.)
- 문제풀이에 소요된 시간, 메모리 (사진 첨부 가능)
<br>
> 문제를 해결하기 위해서 어떻게 접근했는지 작성해주세요.
> 문제를 어떻게 해결했는지를 작성해주세요.
> 피드백 받고싶은 부분을 작성해주세요.
> 자율적으로 본인의 회고를 작성해주세요.
<br>

[2차시]안도형  BOJ 1325, BOJ 3584

---

남우성/5차시/17144.java
남우성/5차시/19236.java

- 문제 링크 : [17144 미세먼지 안녕!](https://www.acmicpc.net/problem/17144)
- 메모리: 36736 KB
- 시간: 356 ms
- 분석한 시간복잡도: O(N^2 * K)
- 이유: 먼지 확산이나 공기 청정기 이동에서 O(N^2)이 들어가는데, 이 때 K만큼 반복
<br>
- 단순 구현문제라고 생각. 다른 알고리즘을 접목할 만한게 없어보였음
- 구현으로 푼다고 하고, 최적화 방안을 모색
- 배열 2개를 선언해 놓고, 연산 + 이동을 한번에 처리 등등…
- 근데 예외상황도 많이 생길거고, 최적화를 한다고 해도 시간 복잡도가 줄어들거나 하지는 않아서 안전하게 요구사항 대로 구현해서 품
- 문제 분석 및 나의 풀이
- 문제 제시 상황 그대로 단순 구현으로 풀이
- 이유
- 다른 알고리즘을 접목 할만한 게 없다고 판단하기도 했고, 최적화 방안도 잘 안 떠오름.
- 그리고 어정쩡한 최적화하면 오히려 반례가 생길 것 같아서..
빡 구현이 될 수록 코드 가독성이나 전체적인 퀄리티가 많이 떨어지네요…. 깔끔한 반복처리나 가독성 향상에도 신경을 쓰면서 연습해야 될 것 같슴다
<br><br>
- 문제 링크 : [19236 청소년 상어](https://www.acmicpc.net/problem/19236)
- 메모리: 14356 KB
- 시간: 116 ms
- 분석한 시간복잡도: O(N^8)...??
- 이유: 각 시행마다 N^2 배열을 탐색 기준 동작이 시행되는데, 이게 최대 4번의 case만큼 나눠질 수 있으니까..? 이게 맞나요..? 시간복잡도 계산이 잘 안 되네요,,
<br>
- …

[5차시] 남우성 - BOJ_17144, BOJ_19236

---

박정훈/5차시/BOJ_17144.java
박정훈/5차시/BOJ_19236.java

- 문제 링크 : [17144번 미세먼지 안녕!](https://www.acmicpc.net/problem/17144)
- 시간 복잡도: O(T * R * C)
<br>
문제에 나온 그대로 구현
- 공기청정기 위치를 저장하여 탐색 과정을 줄인다.
- 동시에 확산이 진행되는 것을 구현하기 위해 원본을 복사한 후 복사본에서 미세먼지가 존재하는 칸을 찾아 확산된 값을 원본 배열에 저장
- 공기청정기가 밀어내는 방향의 역순으로 저장(겹치는 부분 해결)
> X
괜히 어설프게 최적화 하려고 미세먼지 위치를 Set으로 관리하려다가 시간만 오래걸리고 해결도 못했습니다.
포기하고 처음부터 다시 푸니 금방 해결할 수 있었네요.
<br>
- 문제 링크 : [19236번 청소년 상어](https://www.acmicpc.net/problem/19236)
- 시간 복잡도: 이런 문제는 계산 어떻게 하는 거죠..?
<br>
- 물고기 클래스를 만들어 관리
- 물고기 이동 이후 상어가 잡아 먹을 수 있는 모든 경우의 수를 재귀 호출로 탐색(DFS + 백트래킹)
1. 사이클 (`cycle()`)
- 1번 물고기부터 차례로 찾아 `moveFish()`를 호출한다.
- 상어의 위치를 찾아 `moveShark()`를 호출한다.
2. 물고기 이동 (`moveFish()`)
- 가지고 있는 방향 `direct`에 0~8까지 더해 8로 나눈 나머지값으로 다음 이동할 방향을 정한다.
- 만약 다음 이동 칸이 이동이 불가능한 칸이라면 다음 방향으로 진행한다.
- 이동이 가능하다면 해당 칸으로 이동한다.
- 빈 칸이라면 해당 방향으로 이동 후 원래 …

[5차시] 박정훈 - 17144번 미세먼지 안녕!, 19236번 청소년 상어

---

안도형/5차시/BOJ_17144.java
안도형/5차시/BOJ_19236.java

- 문제 링크 : [바로가기](https://www.acmicpc.net/problem/17144)
<html>
<body>
메모리 | 시간 | 시간 복잡도 | 공간 복잡도
-- | -- | -- | --
19048KB | 324ms | O(T x R × C) | O(R × C)
</body>
</html>
<br>
- 단순하게 구현해도 최대 250만 번이 실행되기 때문에 최적화를 하지 않아도 된다고 생각되었습니다.
- 각 맵을 순회하면서 먼지를 네 방향으로 5로 나눈 값만 큼 더 해주고 확산된 양 만큼 현재 위치의 먼지를 빼준다.
- 확산은 확산 될 먼지 양을 누적해 두고 마지막에 값을 넣어줘야 값이 정확하게 들어간다.
- 이후 위쪽은 반 시계, 아래는 시계 방향으로 공기를 순환시켜준다. 이때 값을 밀어줄 땐 역 방향으로 진행하였다.
- 반 시계 방향에선 시계 방향으로 접근을 해 값을 밀어주었다.
- 먼지 확산 단계에서는 각 칸의 먼지를 상하좌우 네 방향으로 확산시킨다.
- 확산될 양은 현재 먼지 / 5이며, 확산 가능한 방향 수에 따라 해당 양을 이웃 칸에 더하고, 원래 칸의 먼지에서 누적된 만큼 빼준다.
- 이때 확산은 중첩될 수 있으므로 별도의 임시 배열(subMap)에 누적한 뒤, 확산이 끝난 후 원래 맵에 반영한다.
- 공기청정기 작동 단계에서는 위쪽 공기청정기는 반시계 방향, 아래쪽 공기청정기는 시계 방향으로 바람을 순환시킨다.
- 순환 과정은 끝에서부터 거꾸로 값을 덮어써서 밀어내는 방식으로 구현하였다.
- 전체 과정은 T초 동안 반복되며, 각 초마다 확산 → 순환 순으로 진행된다.
- …

5차시 17144, 19236

---

박정훈/6차시/BOJ_2665.java

- 문제 링크 : [2665번 미로만들기](https://www.acmicpc.net/problem/2665)
- 시간 복잡도: O(N^2)
<br>
가중치를 이용한 bfs
검은 방을 방문한 횟수를 저장해 이 값을 기준으로 우선순위 큐에 삽입 후 차례로 탐색
X
다익스트라인지도 몰랐고 그냥 BFS인 줄 알았습니다.
알아보니 0-1 BFS 라는 것도 있었네요
<br>

[6차시] 박정훈 - 2665번 미로만들기

---

천보성/7차시/BOJ_1238.java

- 문제 링크 : (https://www.acmicpc.net/problem/1238)
<br>
> 문제의 요점은 다음과 같았습니다.
1. 단방향 그래프
2. 마을에서 X까지 가는 것
3. X에서 마을까지 가는 것
2번과 3번을 더해서 최댓값을 구하는 문제입니다.
이를 간단하게 생각하면 간선의 정보를 역방향으로 저장하면 마을에서 X까지의 거리를 구할 수 있고
간선의 정보를 원래 방향으로 저장하면 X에서 마을까지의 거리들을 구할 수 있었습니다.
> 간선 정보를 저장하는 2개의 ArrayList<ArrayList<Edge>> 필요
X에서 다익스트라를 역방향으로 1번, 순방향으로 1번해서 
dist1[index] + dist2[index] 의 최댓값 구하기
> 
> 문제 자체는 쉬우나 어떻게 최적화 하느냐가 관건인 문제인 것 같습니다.
<br>

[7차시] 천보성 - BOJ_1238

---

박정훈/7차시/BOJ_1238.java

- 문제 링크 : [1238번 파티](https://www.acmicpc.net/problem/1238)
- 시간 복잡도: O(N*MlogN)
<br>
모든 노드를 시작점으로 다익스트라 탐색, 도착점에서 다시 각 노드로 돌아오는 시간 합산
1. 각 노드를 시작점으로 도착점까지 모든 노드 다익스트라 탐색
2. 시작점 -> 도착점 다익스트라
- 도착점에 도달 시 도착점을 시작점으로 시작점까지 재귀 탐색
3. 다시 시작점에 왔다면 총합을 반환
지금 풀이가 문제에서 요구하는 풀이법이 맞을까요?
X
<br>

[7차시] 박정훈 - BOJ_1238

---

천보성/10차시/BOJ_12100.java

- 문제 링크 : (https://www.acmicpc.net/problem/12100)
<br>
구현이기에 문제를 분석해 기능 별로 나눴습니다.
- 움직이는 로직 (상하좌우)
- 블록이 합쳐지는 로직
- 이미 한번 합쳤던 건지 확인 (boolean[] merged)
- 최대 5번 이동 (dfs 확인)
상하좌우 움직이는 로직을 나눠서 구현
한줄씩 temp 배열을 선언해서 합치고 원본에 옮겨담기
5번 이동 후 최댓값 갱신
> 
move 로직을 하나로 통합하고 싶었는데 방도가 생각이 안 나서 분리를 했네요.. 
저도 B형 준비로 인해 이제 1문제씩 하게 됐습니다.
유형이 달라도 너무 다르더라고요..
<br>

[10차시] 천보성 - BOJ_12100

---

박정훈/10차시/BOJ_12100.java

- 문제 링크 : [2048 (Easy)](https://www.acmicpc.net/problem/12100)
- 시간 복잡도: O(N^2)
<br>
- 완전탐색, 시뮬레이션 구현
- 상, 하, 좌, 우 모든 방향으로 이동했을 경우 모두 탐색
- 보드판 복사를 통해 백트래킹
- 이동 방향에 따라 도착하는 순서대로 큐에 삽입
- 큐에 있는 요소에 따라 합치거나 그대로 보드판에 배치
- 이미 합쳐진 경우 다음 숫자에 합쳐지지 않는 것이 보장됨
X
숫자 합치는 부분에서 구현하다가 복잡해져서 다른 방법을 생각하다보니
트럭 문제에서 큐를 이용하면 이동의 구현을 편하게 할 수 있던 것이 생각이나 큐를 이용해서 구현했습니다.
훨씬 간단하게 구현이 가능하네요
<br>

[10차시] 박정훈 - BOJ_12100

---

안도형/11차시/BOJ_2110.java
안도형/11차시/BOJ_2792.java
안도형/8차시/BOJ_11559.java

- 문제 링크 : [바로가기](https://www.acmicpc.net/problem/11559)
<br>
- 단순한 구현 문제라고 생각되었다. bfs방식을 이용하여 풀게 되었다.
- 4개 이상 블록이 뭉쳐있는 것을 지워주고 위에 있는 블록을 아래로 내려준다. (반복)
- 해당 위치의 블록이 존재한다면 4개 이상 같은 블록으로 뭉쳐져 있는지 확인` `visited`` 로 방문자 처리
- 뭉쳐져 있는 블록을 따로 저장해 두고 4개 이상인 것만 지워준다.
- 전체 맵을 조회해 각 열 아래에 빈 공간이 있다면 블록을 아래로 이동 시켜준다.
- 위의 방법을 더 이상 4개 이상 블록이 안나올 때 까지 반복한다.
- 추가적인 최적화가 가능 할 것 같다.
- 블록이 지워진 열만 검사하는 방식으로 빈 공간을 채워주기, 
- 맵에 블록이 있는 위치만 저장해두고 저장된 위치만 검사하는 방식
<br>

[8차시] 안도형 - 11559번

---

이승형/9차시/BOJ_13975.java
이승형/9차시/BOJ_15903.java

- 문제 링크 : https://www.acmicpc.net/problem/15903
- 문제풀이에 소요된 시간, 메모리 (사진 첨부 가능)
O(Mlog(N))
<br>
> 결과를 가장 작게 만드는 것은 모든 과정을 가장 작게 만들어나간 것의 결과
> 1. pq에 모두 삽입
> 2. 2개 poll
> 3. 합한 수를 2개 넣음
> 크게 어려움은 없었던 것 같습니다!
> 최소값, 최대값 찾기는 pq를 활용 생각하기
<br>
---
- 문제 링크 : https://www.acmicpc.net/problem/13975
- 문제풀이에 소요된 시간, 메모리 (사진 첨부 가능)
<br>
> 문제를 읽고, 예시가 큰수+작은수 를 만들어서 합산하는 거로 잘못 접근
> 실버문제와 같이 결과를 작게 만드는 것은 모든 과정을 작게 만들어나간 결과...
> 1. pq에 모두 삽입
> 2. 2개 빼서 합산, 합산은 따로 sum에 더함
> 3. pq에 다시 삽입
> 풀고나니 큰 어려움은 없는 문제였습니다. 문제에 낚여서 고민을 너무 오래한....
> '문제를 잘 읽자' + 문제에 낚이지 말자..... 신념 갖기
<br>

[9차시] 이승형 - BOJ_15903, BOJ_13975

---

박정훈/11차시/BOJ_2110.java

- 문제 링크 : [2110번 공유기 설치](https://www.acmicpc.net/problem/2110)
- 시간 복잡도: O(NlogM) (M은 집의 최대 거리)
<br>
이분탐색을 이용해 가능한 최대 거리 탐색
- 집의 좌표를 정렬
- left를 0, right를 집의 최대 거리로 설정한 후 이분탐색
- mid가 공유기를 설치할 거리
- 이전에 설치한 집과 현재 집 사이의 거리가 mid보다 크면 현재 집에 설치
- 설치한 개수가 C보다 크거나 같다면
- 설치 거리를 벌려서 가능한 지 탐색
- mid 값을 답으로 저장
- mid의 오른쪽 범위에서 탐색
- 작다면
- 설치 거리를 좁혀서 탐색
- mid의 왼쪽 범위에서 탐색
X
이분탐색이라는 점은 알았는데 해결하는 데에 시간이 걸렸습니다.
가장 인접한 두 공유기 사이의 거리를 최대로 => 이 부분이 잘 이해가 가지 않아 문제를 잘못 풀이했고 
집의 좌표들로 이분탐색을 진행해서 mid로부터 거리가 더 작은 쪽에서 공유기를 설치하는 식으로 풀었으나 여러 케이스에서 문제가 발생하는데 해결 방안이 없어 이 풀이가 아니라고 생각했습니다.
그래서 ai에게 힌트를 받았고 그 힌트에서 문제에서 어떤 것을 원하는 지 이해하고 문제를 풀었습니다.
알고리즘이 아니라 국어 공부부터 해야겠네요
<br>

[11차시] 박정훈 - BOJ_2110

---

천보성/12차시/BOJ_17471.java
천보성/12차시/SWEA_2117.java

- 문제 링크 : (https://www.acmicpc.net/problem/17471)
<br>
초기에는 bfs 없이 dfs로만 접근했으나 그러면 방문하지 않는 노드도 생기더라고요.
bfs를 섞어서 그룹이 연결됐는지 확인하는 것이 필요하다고 생각했습니다.
- dfs로 그룹의 조합을 결정
- boolean 배열로 true는 1번 그룹, false 는 2번 그룹
- bfs로 그룹이 연결됐는지 확인
- getDiffPeople 함수로 그룹별 인구수 차이 얻기
> 최적화 할 수  있을까요??
> 어디서 잘못된 건지 몰라서 디버깅을 한참 돌렸었습니다..
<br>
- 문제 링크 : (https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5V61LqAf8DFAWu)
<br>
단순한 구현이라 판단
list에 집 위치를 다 저장하고 완전탐색으로 맨해튼 거리를 확인하여 값을 갱신해나가면 된다고 생각했습니다.
- list에 집 위치 저장
- 2중 for문으로 방범 서비스의 중앙 위치 옮기기
- 맨해튼 거리로 범위 k 내에 있는지 확인
- 손해를 안본다면 count 와 max 값 비교
> list에 저장안하고 다 확인하는 것이 성능적으로 더 좋네요..

[12차시] 천보성 - BOJ_17471, SWEA_2117

---

14차시/swea_1249.java
14차시/swea_2105.java

- 문제 링크 : [swea_1249 보급](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV15QRX6APsCFAYD)
- 분석한 시간복잡도: O(NlogN)..?
- 이유: 다익스트라가 O(V+E)logV)니까 O(NlogN)이지 않을까..? 생각
<br>
<접근 방식(문제 풀이까지 고민한 내용들)>
- 문제보고 처음 든 생각은 DP인데, 바로 고쳐먹음
- DP로 풀이하려면 최적의 경로가 오른쪽 혹은 아래로 이동만 한정되어 있을 때만 가능할 것 같았음
-  즉 지그재그로 돌아가는 경우가 최적일 경우에는 DP로 풀이 불가능
=> PQ를 사용한 다익스트라로 풀이
<문제 풀이 요약>
- PQ에 각 좌표를 넣음. 여기서 정렬은 해당 위치까지 도달하기 위해 필요한 cost
=> 위치에서 갈 수 있는 경우 pq에 넣어가며 진행 => 최종 목적지에 도달하면 바로 종료
(PQ라서 처음 도달한 시점이 최적이 보장된다고 생각함)
<br><br>
- 문제 링크 : [swea_2105 디저트 카페](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5VwAr6APYDFAWu)
- 분석한 시간복잡도: O(N^4)..?
- 이유: 전체 인덱스에 대해 N^2 탐색을 더 진행하니까 N^4
<br>
- 보자마자 단순 구현이라고 생각함. 최적화 방법 없을 것 같앗음
- 먼저 시작 인덱스를 상단 꼭짓점으로 잡음
- 이후 왼쪽 꼭짓점을 설정
- 이후 전체 …

[14차시] 남우성 - SWEA_1249, SWEA_2105

---

남우성/17차시/swea_1767.java
남우성/17차시/swea_5653.java

- 문제 링크 : [swea_1767 프로세서 연결하기](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV4suNtaXFEDFAUf&)
- 분석한 시간복잡도: O(5^12)
- 이유: 각 5개의 case마다 재귀로 전개 ⇒ 최대 5^12 필요
<br>
<접근 방식(문제 풀이까지 고민한 내용들)>
- 완탐 및 구현으로 생각
<문제 풀이 요약>
- 문제 분석 및 나의 풀이
- 각 core별로 5개의 가지 수가 존재, 연결하지 않음, 상하좌우 연결
- 각 5개의 case마다 재귀로 전개 ⇒ 최대 5^12 필요
- 여기서 만약 남은 코어를 전부 포함해도 현재 result를 넘기지 못하면 가지치기
- 사용한 알고리즘 및 자료구조
- 완탐 + 가지치기
<리뷰 요청 포인트>
- 재귀를 잘 안 써서 파라미터로 배열 넘길 때, 배열을 언제 복사할 지, 언제 리턴할지, 배열을 넘길지 인덱스만 넘길지가 많이 혼동되네요…. 재귀 연습을 좀 해야 될 거 같네요..ㅠ
<br><br>
- 문제 링크 : [swea_5653 줄기세포 배양](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRJ8EKe48DFAUo)
- 분석한 시간복잡도: O(4^K * N)..?
- 이유: N이 최대 4개씩 증식할 수 있는데, 이게 K번 반복되니까..?
<br>
- 보고 시뮬레이션 문제라 생각
- 알고리즘 쓸 것도 없고 그냥 진짜 문제대로 시뮬레이션 돌리면서 결과 …

[17 차시] 남우성 - 프로세서 연결하기, 줄기세포 배양

---

천보성/17차시/SWEA_1767.java
천보성/17차시/SWEA_5653.java

- 문제 링크 : [바로가기](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV4suNtaXFEDFAUf)
<br>
단순 구현, 리스트에 프로세서 위치를 담아두고 4방향으로 완전 탐색을 돌려도 충분히 가능할 거라 생각했습니다
- 리스트에 프로세서 위치 저장, 모서리 부분은 저장 안함
-  dfs로 프로세서마다 전선 설치, 이미 설치한 곳이거나 설치 위치에 프로세서가 존재한다면 설치 불가능
- 가지치기
<br>
- 문제 링크 : [바로가기](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRJ8EKe48DFAUo)
<br>
단순 구현, 번식할때의 우선 처리가 가장 중요하다고 생각했습니다.
- pq를 사용하여 줄기 세포들의 우선순위 설정
-   set을 사용하여 중복 좌표 방지
<br>

[17차시] 천보성 - 프로세서 연결하기, 줄기세포 배양

---

남우성/18차시/swea_1949.java
남우성/18차시/swea_5656.java

- 문제 링크 : [swea_1949 등산로 조성](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PoOKKAPIDFAUq)
- 분석한 시간복잡도: O(K * N^2)
- 이유: 봉우리 K개 마다 N^2 크기의 배열 탐색 가능
<br>
<접근 방식(문제 풀이까지 고민한 내용들)>
- dfs, bfs를  활용한 구현문제라고 생각함
<문제 풀이 요약>
- 문제 분석 및 나의 풀이
- 먼저 봉우리 K를 저장
- 각 K마다 dfs로 탐색 → 만약 못 가는 경우 change 여부를 검사하고, 아직 chance를 안 섰으면 쓰고 다음 재귀 호출
- 사용한 알고리즘 및 자료구조
- 구현 + dfs
- 이유
- 처음에는 PQ를 써서 가장 최적부터 탐색할까 했는데, 전부 다 검사가 필요한 거라 PQ 쓸 의미도 없고 오히려 오래 걸릴 거 같아서 단순 dfs로 풀이
<기타 회고>
- 이 문제는 디버깅하면서 2개가 문제였음
- Set의 경우 동일성 검사를 위해 equals와 hashCode 2개의 메서드를 모두 overriding해야 되는데, equals만 오버라이딩 함….
- 무조건 K만큼 깍아야 되는 줄 알았는데, 최대 K까지 깍을 수 있는 거였음…. 문제를 잘 읽자…
<br><br>
- 문제 링크 : [swea_5656 벽돌 깨기](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRQm6qfL0DFAUo)
- 분석한 시간복잡도: …

[18 차시] 남우성 - 등산로 조성, 벽돌 깨기

---

안도형/20차시/BOJ_1202.java

- 문제 링크 : [바로가기](https://www.acmicpc.net/problem/1202)
- <img width="528" height="44" alt="image" src="https://github.com/user-attachments/assets/a3e556c7-9571-4b29-b3d2-ab476d5abdc5" />
<br>
> 보석을 1개만 가방에 넣을 수 있기 때문에 무게 순으로 오름차 순으로 정렬 후 
> 해당 가방이 허용할 무게 만큼 pq에 넣어 처리하면 되겠다고 생각했습니다.
> 총 탐색 시간 복잡도가 최대 N+K+NlogN + KlogK 라 충분했습니다.
> 일단 최적화를 최대한 해봤는데 0.7초도 있어서 더 최적화 할 방법이 뭐가있을까요?
> B형 하느라 자료구조만 잘 알아도 쉽게 푸는 문제라고 생각합니다.
<br>

[20차시] 안도형- 1202번 보석 도둑

---

안도형/23차시/BOJ_8980.java
안도형/24차시/BOJ_1949

- 문제 링크 : [바로가기](https://www.acmicpc.net/problem/8980)
<br>
> 받는 마을 기준으로 오른차순 정렬 같으면 보내는 마을 기준 오름차순으로 정렬
> 각 마을마다 트럭에 실려있는 박스를 저장하면서 총 배송량 누적
> 처음에 그냥 변수 하나에 박스를 빼거나 더해줘서 트럭에 실려있는 박스를 계산 했다가 이러면 중간에 트럭에 실린 박스의 수가 재대로 빠지지 않았습니다.
<br>

 [23차시] 안도형 - 8980번 택배

---

남우성/25차시/1517.java

- 문제 링크 : [1517](https://www.acmicpc.net/problem/1517)
- 문제풀이에 소요된 시간, 메모리 (사진 첨부 가능)
<br>
- 처음에는 단순 선형탐색 밖에 안 떠올라서 일단 그렇게 풀었는데 시간초과
- 선형탐색이면 O(N^2)인데, 입력값을 보면 O(NlogN) 내의 알고리즘을 구상해야 했음
- 머지소트를 활용. 머지소트는 O(NlogN)이므로 시간안에 가능(과거 봤던 풀이를 참고해서 풀었음)
- 머지소트를 해가면서 오른쪽 파트가 들어갈 때, 왼쪽 파트의 개수만큼 reuslt에 ++
(이 수치만큼 순서를 바꿔야 된다고 판단)
<br>

 [25차시] 남우성 - 1517번 버블 소트
